name = "ai-uploader"
compatibility_date = "2024-12-01"

[vars]
DOWNLOAD_TTL_MINUTES = "15"
DOWNLOAD_TTL_MAX_MINUTES = "120"

[[d1_databases]]
binding = "DB"
database_name = "ai_uploader_db"
database_id = "495ad2cd-48b5-46b6-85b0-2a08a7639ea4"
preview_database_id = "495ad2cd-48b5-46b6-85b0-2a08a7639ea4"

[[r2_buckets]]
binding = "R2"
bucket_name = "ai-uploader"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "rate_limit_kv"
preview_id = "rate_limit_kv"

# Pages Functions configuration
[build]
command = "npm run build"
cwd = "web"
watch_dir = "web"

[build.upload]
format = "service-worker"

